# Generated by Django 2.0 on 2018-01-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_auto_20180103_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='date_added',
        ),
    ]
